### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by tschoonj**
Ciao Carmelo!

I have been asked by Giannantonio Cibin from our B18 beamline to install your package onto our Linux systems. In order to do so, I had to make a couple of changes and thought that you may be interested in merging them into your repository.

One of the main modifications is the setup.py script: I created a new that is based on setuptools, and renamed your old one to setupWin.py as it only seems relevant to the Windows OS.

Apart from that:
- Provide support for the Unix style `HOME` environment variable, necessary since `HOMEDRIVE` and `HOMEPATH` only exist on Windows
- Support for PyMca 5 (specfile)
- Add gitignore file
- Delete redundant *pyc files
- Rename `Exapy.py` to `exapy.py` (I think your files were on a case-insensitive filesystem)

Let me know if you need more information

Best,

Tom

Diamond Light Source

### CODE REVIEW

**Comment by Prestipino** [comment]
Hi Tom 
I check asap the variation and I'll merge
Thanks 
Carmelo

**Comment by tschoonj** [comment]
We have a couple more fixes lined up. Don't merge in yet please

Thanks

Tom

**Comment by Prestipino** [comment]
OK

On Thu, May 26, 2016 at 6:21 PM, Tom Schoonjans notifications@github.com
wrote:

> We have a couple more fixes lined up. Don't merge in yet please
> 
> Thanks
> 
> Tom
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/soonready/PrestoPronto/pull/2#issuecomment-221921202

## 

Carmelo Prestipino
Sciences Chimiques de Rennes, UMR 6226
Solid State and Materials Chemistry group (CSM)
Campus de Beaulieu, Bât 10B, bureau 123
263 avenue du Général Leclerc
F-35042 RENNES
France
Tel: (+33) 22323 6531
FAX: (+33) 22323 5959

**Comment by Prestipino** [comment]
And Thanks a lot,

On Fri, May 27, 2016 at 12:57 PM, Carmelo Prestipino <
carmelo.prestipino@univ-rennes1.fr> wrote:

> OK
> 
> On Thu, May 26, 2016 at 6:21 PM, Tom Schoonjans notifications@github.com
> wrote:
> 
> > We have a couple more fixes lined up. Don't merge in yet please
> > 
> > Thanks
> > 
> > Tom
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/soonready/PrestoPronto/pull/2#issuecomment-221921202
> 
> ## 
> 
> Carmelo Prestipino
> Sciences Chimiques de Rennes, UMR 6226
> Solid State and Materials Chemistry group (CSM)
> Campus de Beaulieu, Bât 10B, bureau 123
> 263 avenue du Général Leclerc
> F-35042 RENNES
> France
> Tel: (+33) 22323 6531
> FAX: (+33) 22323 5959

## 

Carmelo Prestipino
Sciences Chimiques de Rennes, UMR 6226
Solid State and Materials Chemistry group (CSM)
Campus de Beaulieu, Bât 10B, bureau 123
263 avenue du Général Leclerc
F-35042 RENNES
France
Tel: (+33) 22323 6531
FAX: (+33) 22323 5959

**Comment by tschoonj** [comment]
Hi Carmelo,

This would be my last change for now. Feel free to merge it in.

We did find another bug, which I couldn't fix: in the `EXAFS-FT` tab the `EXAFS params` and `FT param` buttons can only be clicked once. Afterwards no action appears to follow.

This may be related to the following errors we got:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/dls_sw/apps/PrestoPronto/1.0.0/lib/python2.7/site-packages/PrestoPronto-1.0.0-py2.7.egg/PPXanes.py", line 621, in XANESparam
    self.XAN_par=XANESparam(self.topX)
  File "/dls_sw/apps/PrestoPronto/1.0.0/lib/python2.7/site-packages/PrestoPronto-1.0.0-py2.7.egg/PPXanes.py", line 137, in __init__
    self.refresh()
  File "/dls_sw/apps/PrestoPronto/1.0.0/lib/python2.7/site-packages/PrestoPronto-1.0.0-py2.7.egg/PPXanes.py", line 199, in refresh
    p1=PPset.spectra[self.num].pre_edge_details.pre1
AttributeError: 'bm29file' object has no attribute 'pre_edge_details'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/dls_sw/apps/PrestoPronto/1.0.0/lib/python2.7/site-packages/PrestoPronto-1.0.0-py2.7.egg/PPExafs.py", line 774, in EXAFSparam
    self.EXE_par=EXAFSparam(self.topX)
  File "/dls_sw/apps/PrestoPronto/1.0.0/lib/python2.7/site-packages/PrestoPronto-1.0.0-py2.7.egg/PPExafs.py", line 174, in __init__
    self.refresh()
  File "/dls_sw/apps/PrestoPronto/1.0.0/lib/python2.7/site-packages/PrestoPronto-1.0.0-py2.7.egg/PPExafs.py", line 270, in refresh
    k1=PPset.spectra[self.num].autobk_details.kmin
AttributeError: 'Group' object has no attribute 'kmin'
```

Many thanks for your software!

Have a great weekend,

Tom

**Comment by tschoonj** [comment]
Grazie!

**Pull request merged**
